# Generated by Django 4.2.7 on 2026-09-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('airtel_money', 'Airtel Money'), ('paychangu', 'Pay Online (PayChangu)'), ('tnm_mpamba', 'TNM Mpamba')], max_length=20),
        ),
    ]
